alertIndex:
  name: aidx
  in: path
  description:
    "The index of the custom alert.  This must be an integer in the
    range from 0..*N* where *N* is the number of custom alerts minus
    1."
  required: true
  schema:
    type: integer
    minimum: 0

filterParam:
  name: filter
  in: query
  description:
    Limit the output of a `GET` request to those members matching
    [FSPEC](ROOT/common/fspec).
  schema:
    type: string

maxDepthParam:
  name: max-depth
  in: query
  description:
    "The depth to which objects are output.  When this limit is
    reached, only the member names are output for objects, not their
    values."
  schema:
    type: integer
    minimum: 0
