openapi: "3.1.0"
info:
  version: "main"
  title: eGauge WebAPI
  description: eGauge Meter API
  license:
    name: Common Documentation License 1.0
    url: https://spdx.org/licenses/CDL-1.0.html
servers:
  - url: https://{devname}.egauge.io/api
    description: The WebAPI server
    variables:
      devname:
        default: eGaugeHQ
paths:
  $ref: "built/paths.yaml"

components:
  parameters:
    $ref: "built/params.yaml"
  securitySchemes:
    ApiKey:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - ApiKey: []

tags:
  $ref: "built/tags.yaml"
