afterParam:
  name: after
  in: query
  description: |
    Limits the output to messages with a timestamp that is newer than
    the value specified by this parameter.  The value must be a
    decimal number and may include a fractional part.  The number is
    interpreted as seconds since the epoch.  For most logs, the epoch
    is the Unix epoch (i.e., seconds since the start of Jan 1, 1970
    UTC).  However, for the [kernel log](op:/log:logKernelGet),
    the epoch is the time the meter was powered up (booted).
  schema:
    type: number
  example: 6.9801816

filterParam:
  name: filter
  in: query
  description: "Response filter string. See
  [Filter-Spec](glossary:Filter-Spec)."
  schema:
    type: string
  example: "{foo,bar}"

maxDepthParam:
  name: max-depth
  in: query
  description: "Limit output depth of the response.  See
    [Max-Depth](glossary:Max-Depth)."
  schema:
    type: integer
    minimum: 1
  example: 2
